role: cluster-init
server: https://51.195.5.176:6443

k3s:
  version: v1.35.5+k3s1

restore:
  enabled: false

rancher:
  values:
    hostname: rancher.manuelzapf.io
    replicas: 1
    ingress:
      tls:
        source: letsEncrypt
    letsEncrypt:
      email: me@manuelzapf.io
      environment: production   # or: staging (for testing)
      ingress:
        class: traefik
