server {
    listen 80;
    server_name _;

    location /from-clusters-to-controlplanes/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /from-clusters-to-controlplanes/index.html;
        location ~* \.html$ {
            add_header Cache-Control "no-store, no-cache, must-revalidate";
        }
    }

    location = / {
        return 301 /from-clusters-to-controlplanes/;
    }
}
