apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: clusters-hcp-demo
  namespace: fleet-local
spec:
  repo: FLEET_REPO_PLACEHOLDER
  branch: main
  paths:
    - fleet/rancher-settings
    - fleet/cdi-operator
    - fleet/cdi-cr
    - fleet/kubevirt-operator
    - fleet/kubevirt-cr
    - fleet/kamaji
    - fleet/capi-kubevirt
    - fleet/capi-kamaji
    - fleet/capi-k3s
    - fleet/k3k
  targets:
    - clusterSelector: {}
