---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: kamaji-kubevirt-cni
  namespace: capi-kamaji-kubevirt
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: kamaji-kubevirt
  resources:
    - name: cni
      kind: ConfigMap
