---
apiVersion: v1
kind: Namespace
metadata:
  name: k3k-simple
  labels:
    cluster-api.cattle.io/rancher-auto-import: "true"
---
apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: simple
  namespace: k3k-simple
spec:
  mode: shared
  servers: 1
  agents: 1
  version: v1.32.6-k3s1
  clusterCIDR: 10.200.0.0/16
  serviceCIDR: 10.201.0.0/16
  expose:
    nodePort: {}
